models:
  AdaBoostClassifier:
    estimator_split:
      train_scoring_split: 0.3
    estimator_upsampling:
      strategy: 1
      k_neighbors: 5
    estimator_parameters_opt:
      scorer: "Recall"
      n_jobs: -1
      n_iter_search: 500
      apply_pca: False
      parameters:
