name: my-template-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - -r file:requirements.txt
    - -r file:requirements-codequality.txt
    - -r file:requirements-pipelines.txt
